name: Latest blog post workflow
on:
  schedule:
    # Runs at 00:00 IST every day
    - cron: '30 18 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "5"
          feed_list: "https://naiyer.dev/all.xml"
